name: Build Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'main/**'
      - 'CMakeLists.txt'
      - 'idf_component.yml'
      - 'diagram.json'
      - 'wokwi.toml'
  workflow_dispatch:

env:
  ESP_IDF_VERSION: 'v5.5-dev'
  PROJECT_NAME: 'monoscope'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          target: esp32c6

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: /
          expect_text: 'Drawing monoscope TV test pattern'
          timeout: 10000

      - name: Take LCD screenshot
        run: |
          mkdir -p screenshots
          wokwi-cli --timeout 8000 --timeout-exit-code 0 --screenshot-part "lcd1" --screenshot-time 7000 --screenshot-file "screenshots/monoscope-pattern.png" "${GITHUB_WORKSPACE}"
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            build/${{ env.PROJECT_NAME }}.bin
            build/${{ env.PROJECT_NAME }}.elf
            screenshots/monoscope-pattern.png
          retention-days: 7

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: lcd-screenshot-${{ github.sha }}
          path: screenshots/monoscope-pattern.png
          retention-days: 7